package music.dexterous.com.dexterousmusic.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import music.dexterous.com.dexterousmusic.database.MusicLibraryTable;

import music.dexterous.com.dexterousmusic.database.MusicLibraryTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicLibraryTableDaoConfig;

    private final MusicLibraryTableDao musicLibraryTableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicLibraryTableDaoConfig = daoConfigMap.get(MusicLibraryTableDao.class).clone();
        musicLibraryTableDaoConfig.initIdentityScope(type);

        musicLibraryTableDao = new MusicLibraryTableDao(musicLibraryTableDaoConfig, this);

        registerDao(MusicLibraryTable.class, musicLibraryTableDao);
    }
    
    public void clear() {
        musicLibraryTableDaoConfig.getIdentityScope().clear();
    }

    public MusicLibraryTableDao getMusicLibraryTableDao() {
        return musicLibraryTableDao;
    }

}
