package music.dexterous.com.dexterousmusic.database;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.os.Parcel;
import android.os.Parcelable;
// KEEP INCLUDES END
/**
 * Entity mapped to table "MUSIC_LIBRARY_TABLE".
 */
public class MusicLibraryTable implements Parcelable {

    private Long id;
    private String SONG_ID;
    private String SONG_TITLE;
    private String SONG_ARTIST;
    private String SONG_ALBUM;
    private String SONG_ALBUM_ARTIST;
    private String SONG_DURATION;
    private String SONG_FILE_PATH;
    private String SONG_TRACK_NUMBER;
    private String SONG_GENRE;
    private String SONG_PLAY_COUNT;
    private String SONG_YEAR;
    private String ALBUMS_COUNT;
    private String SONGS_COUNT;
    private String GENRES_SONG_COUNT;
    private String SONG_LAST_MODIFIED;
    private String SONG_SCANNED;
    private String BLACKLIST_STATUS;
    private String ADDED_TIMESTAMP;
    private String RATING;
    private String LAST_PLAYED_TIMESTAMP;
    private String SONG_SOURCE;
    private String SONG_ALBUM_ART_PATH;
    private String SONG_DELETED;
    private String ARTIST_ART_LOCATION;
    private String ALBUM_ID;
    private String ARTIST_ID;
    private String GENRE_ID;
    private String GENRE_SONG_COUNT;
    private String LOCAL_COPY_PATH;
    private String LIBRARIES;
    private String SAVED_POSITION;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MusicLibraryTable() {
    }

    public MusicLibraryTable(Long id) {
        this.id = id;
    }

    public MusicLibraryTable(Long id, String SONG_ID, String SONG_TITLE, String SONG_ARTIST, String SONG_ALBUM, String SONG_ALBUM_ARTIST, String SONG_DURATION, String SONG_FILE_PATH, String SONG_TRACK_NUMBER, String SONG_GENRE, String SONG_PLAY_COUNT, String SONG_YEAR, String ALBUMS_COUNT, String SONGS_COUNT, String GENRES_SONG_COUNT, String SONG_LAST_MODIFIED, String SONG_SCANNED, String BLACKLIST_STATUS, String ADDED_TIMESTAMP, String RATING, String LAST_PLAYED_TIMESTAMP, String SONG_SOURCE, String SONG_ALBUM_ART_PATH, String SONG_DELETED, String ARTIST_ART_LOCATION, String ALBUM_ID, String ARTIST_ID, String GENRE_ID, String GENRE_SONG_COUNT, String LOCAL_COPY_PATH, String LIBRARIES, String SAVED_POSITION) {
        this.id = id;
        this.SONG_ID = SONG_ID;
        this.SONG_TITLE = SONG_TITLE;
        this.SONG_ARTIST = SONG_ARTIST;
        this.SONG_ALBUM = SONG_ALBUM;
        this.SONG_ALBUM_ARTIST = SONG_ALBUM_ARTIST;
        this.SONG_DURATION = SONG_DURATION;
        this.SONG_FILE_PATH = SONG_FILE_PATH;
        this.SONG_TRACK_NUMBER = SONG_TRACK_NUMBER;
        this.SONG_GENRE = SONG_GENRE;
        this.SONG_PLAY_COUNT = SONG_PLAY_COUNT;
        this.SONG_YEAR = SONG_YEAR;
        this.ALBUMS_COUNT = ALBUMS_COUNT;
        this.SONGS_COUNT = SONGS_COUNT;
        this.GENRES_SONG_COUNT = GENRES_SONG_COUNT;
        this.SONG_LAST_MODIFIED = SONG_LAST_MODIFIED;
        this.SONG_SCANNED = SONG_SCANNED;
        this.BLACKLIST_STATUS = BLACKLIST_STATUS;
        this.ADDED_TIMESTAMP = ADDED_TIMESTAMP;
        this.RATING = RATING;
        this.LAST_PLAYED_TIMESTAMP = LAST_PLAYED_TIMESTAMP;
        this.SONG_SOURCE = SONG_SOURCE;
        this.SONG_ALBUM_ART_PATH = SONG_ALBUM_ART_PATH;
        this.SONG_DELETED = SONG_DELETED;
        this.ARTIST_ART_LOCATION = ARTIST_ART_LOCATION;
        this.ALBUM_ID = ALBUM_ID;
        this.ARTIST_ID = ARTIST_ID;
        this.GENRE_ID = GENRE_ID;
        this.GENRE_SONG_COUNT = GENRE_SONG_COUNT;
        this.LOCAL_COPY_PATH = LOCAL_COPY_PATH;
        this.LIBRARIES = LIBRARIES;
        this.SAVED_POSITION = SAVED_POSITION;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSONG_ID() {
        return SONG_ID;
    }

    public void setSONG_ID(String SONG_ID) {
        this.SONG_ID = SONG_ID;
    }

    public String getSONG_TITLE() {
        return SONG_TITLE;
    }

    public void setSONG_TITLE(String SONG_TITLE) {
        this.SONG_TITLE = SONG_TITLE;
    }

    public String getSONG_ARTIST() {
        return SONG_ARTIST;
    }

    public void setSONG_ARTIST(String SONG_ARTIST) {
        this.SONG_ARTIST = SONG_ARTIST;
    }

    public String getSONG_ALBUM() {
        return SONG_ALBUM;
    }

    public void setSONG_ALBUM(String SONG_ALBUM) {
        this.SONG_ALBUM = SONG_ALBUM;
    }

    public String getSONG_ALBUM_ARTIST() {
        return SONG_ALBUM_ARTIST;
    }

    public void setSONG_ALBUM_ARTIST(String SONG_ALBUM_ARTIST) {
        this.SONG_ALBUM_ARTIST = SONG_ALBUM_ARTIST;
    }

    public String getSONG_DURATION() {
        return SONG_DURATION;
    }

    public void setSONG_DURATION(String SONG_DURATION) {
        this.SONG_DURATION = SONG_DURATION;
    }

    public String getSONG_FILE_PATH() {
        return SONG_FILE_PATH;
    }

    public void setSONG_FILE_PATH(String SONG_FILE_PATH) {
        this.SONG_FILE_PATH = SONG_FILE_PATH;
    }

    public String getSONG_TRACK_NUMBER() {
        return SONG_TRACK_NUMBER;
    }

    public void setSONG_TRACK_NUMBER(String SONG_TRACK_NUMBER) {
        this.SONG_TRACK_NUMBER = SONG_TRACK_NUMBER;
    }

    public String getSONG_GENRE() {
        return SONG_GENRE;
    }

    public void setSONG_GENRE(String SONG_GENRE) {
        this.SONG_GENRE = SONG_GENRE;
    }

    public String getSONG_PLAY_COUNT() {
        return SONG_PLAY_COUNT;
    }

    public void setSONG_PLAY_COUNT(String SONG_PLAY_COUNT) {
        this.SONG_PLAY_COUNT = SONG_PLAY_COUNT;
    }

    public String getSONG_YEAR() {
        return SONG_YEAR;
    }

    public void setSONG_YEAR(String SONG_YEAR) {
        this.SONG_YEAR = SONG_YEAR;
    }

    public String getALBUMS_COUNT() {
        return ALBUMS_COUNT;
    }

    public void setALBUMS_COUNT(String ALBUMS_COUNT) {
        this.ALBUMS_COUNT = ALBUMS_COUNT;
    }

    public String getSONGS_COUNT() {
        return SONGS_COUNT;
    }

    public void setSONGS_COUNT(String SONGS_COUNT) {
        this.SONGS_COUNT = SONGS_COUNT;
    }

    public String getGENRES_SONG_COUNT() {
        return GENRES_SONG_COUNT;
    }

    public void setGENRES_SONG_COUNT(String GENRES_SONG_COUNT) {
        this.GENRES_SONG_COUNT = GENRES_SONG_COUNT;
    }

    public String getSONG_LAST_MODIFIED() {
        return SONG_LAST_MODIFIED;
    }

    public void setSONG_LAST_MODIFIED(String SONG_LAST_MODIFIED) {
        this.SONG_LAST_MODIFIED = SONG_LAST_MODIFIED;
    }

    public String getSONG_SCANNED() {
        return SONG_SCANNED;
    }

    public void setSONG_SCANNED(String SONG_SCANNED) {
        this.SONG_SCANNED = SONG_SCANNED;
    }

    public String getBLACKLIST_STATUS() {
        return BLACKLIST_STATUS;
    }

    public void setBLACKLIST_STATUS(String BLACKLIST_STATUS) {
        this.BLACKLIST_STATUS = BLACKLIST_STATUS;
    }

    public String getADDED_TIMESTAMP() {
        return ADDED_TIMESTAMP;
    }

    public void setADDED_TIMESTAMP(String ADDED_TIMESTAMP) {
        this.ADDED_TIMESTAMP = ADDED_TIMESTAMP;
    }

    public String getRATING() {
        return RATING;
    }

    public void setRATING(String RATING) {
        this.RATING = RATING;
    }

    public String getLAST_PLAYED_TIMESTAMP() {
        return LAST_PLAYED_TIMESTAMP;
    }

    public void setLAST_PLAYED_TIMESTAMP(String LAST_PLAYED_TIMESTAMP) {
        this.LAST_PLAYED_TIMESTAMP = LAST_PLAYED_TIMESTAMP;
    }

    public String getSONG_SOURCE() {
        return SONG_SOURCE;
    }

    public void setSONG_SOURCE(String SONG_SOURCE) {
        this.SONG_SOURCE = SONG_SOURCE;
    }

    public String getSONG_ALBUM_ART_PATH() {
        return SONG_ALBUM_ART_PATH;
    }

    public void setSONG_ALBUM_ART_PATH(String SONG_ALBUM_ART_PATH) {
        this.SONG_ALBUM_ART_PATH = SONG_ALBUM_ART_PATH;
    }

    public String getSONG_DELETED() {
        return SONG_DELETED;
    }

    public void setSONG_DELETED(String SONG_DELETED) {
        this.SONG_DELETED = SONG_DELETED;
    }

    public String getARTIST_ART_LOCATION() {
        return ARTIST_ART_LOCATION;
    }

    public void setARTIST_ART_LOCATION(String ARTIST_ART_LOCATION) {
        this.ARTIST_ART_LOCATION = ARTIST_ART_LOCATION;
    }

    public String getALBUM_ID() {
        return ALBUM_ID;
    }

    public void setALBUM_ID(String ALBUM_ID) {
        this.ALBUM_ID = ALBUM_ID;
    }

    public String getARTIST_ID() {
        return ARTIST_ID;
    }

    public void setARTIST_ID(String ARTIST_ID) {
        this.ARTIST_ID = ARTIST_ID;
    }

    public String getGENRE_ID() {
        return GENRE_ID;
    }

    public void setGENRE_ID(String GENRE_ID) {
        this.GENRE_ID = GENRE_ID;
    }

    public String getGENRE_SONG_COUNT() {
        return GENRE_SONG_COUNT;
    }

    public void setGENRE_SONG_COUNT(String GENRE_SONG_COUNT) {
        this.GENRE_SONG_COUNT = GENRE_SONG_COUNT;
    }

    public String getLOCAL_COPY_PATH() {
        return LOCAL_COPY_PATH;
    }

    public void setLOCAL_COPY_PATH(String LOCAL_COPY_PATH) {
        this.LOCAL_COPY_PATH = LOCAL_COPY_PATH;
    }

    public String getLIBRARIES() {
        return LIBRARIES;
    }

    public void setLIBRARIES(String LIBRARIES) {
        this.LIBRARIES = LIBRARIES;
    }

    public String getSAVED_POSITION() {
        return SAVED_POSITION;
    }

    public void setSAVED_POSITION(String SAVED_POSITION) {
        this.SAVED_POSITION = SAVED_POSITION;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.SONG_ID);
        dest.writeString(this.SONG_TITLE);
        dest.writeString(this.SONG_ARTIST);
        dest.writeString(this.SONG_ALBUM);
        dest.writeString(this.SONG_ALBUM_ARTIST);
        dest.writeString(this.SONG_DURATION);
        dest.writeString(this.SONG_FILE_PATH);
        dest.writeString(this.SONG_TRACK_NUMBER);
        dest.writeString(this.SONG_GENRE);
        dest.writeString(this.SONG_PLAY_COUNT);
        dest.writeString(this.SONG_YEAR);
        dest.writeString(this.ALBUMS_COUNT);
        dest.writeString(this.SONGS_COUNT);
        dest.writeString(this.GENRES_SONG_COUNT);
        dest.writeString(this.SONG_LAST_MODIFIED);
        dest.writeString(this.SONG_SCANNED);
        dest.writeString(this.BLACKLIST_STATUS);
        dest.writeString(this.ADDED_TIMESTAMP);
        dest.writeString(this.RATING);
        dest.writeString(this.LAST_PLAYED_TIMESTAMP);
        dest.writeString(this.SONG_SOURCE);
        dest.writeString(this.SONG_ALBUM_ART_PATH);
        dest.writeString(this.SONG_DELETED);
        dest.writeString(this.ARTIST_ART_LOCATION);
        dest.writeString(this.ALBUM_ID);
        dest.writeString(this.ARTIST_ID);
        dest.writeString(this.GENRE_ID);
        dest.writeString(this.GENRE_SONG_COUNT);
        dest.writeString(this.LOCAL_COPY_PATH);
        dest.writeString(this.LIBRARIES);
        dest.writeString(this.SAVED_POSITION);
    }

    protected MusicLibraryTable(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.SONG_ID = in.readString();
        this.SONG_TITLE = in.readString();
        this.SONG_ARTIST = in.readString();
        this.SONG_ALBUM = in.readString();
        this.SONG_ALBUM_ARTIST = in.readString();
        this.SONG_DURATION = in.readString();
        this.SONG_FILE_PATH = in.readString();
        this.SONG_TRACK_NUMBER = in.readString();
        this.SONG_GENRE = in.readString();
        this.SONG_PLAY_COUNT = in.readString();
        this.SONG_YEAR = in.readString();
        this.ALBUMS_COUNT = in.readString();
        this.SONGS_COUNT = in.readString();
        this.GENRES_SONG_COUNT = in.readString();
        this.SONG_LAST_MODIFIED = in.readString();
        this.SONG_SCANNED = in.readString();
        this.BLACKLIST_STATUS = in.readString();
        this.ADDED_TIMESTAMP = in.readString();
        this.RATING = in.readString();
        this.LAST_PLAYED_TIMESTAMP = in.readString();
        this.SONG_SOURCE = in.readString();
        this.SONG_ALBUM_ART_PATH = in.readString();
        this.SONG_DELETED = in.readString();
        this.ARTIST_ART_LOCATION = in.readString();
        this.ALBUM_ID = in.readString();
        this.ARTIST_ID = in.readString();
        this.GENRE_ID = in.readString();
        this.GENRE_SONG_COUNT = in.readString();
        this.LOCAL_COPY_PATH = in.readString();
        this.LIBRARIES = in.readString();
        this.SAVED_POSITION = in.readString();
    }

    public static final Creator<MusicLibraryTable> CREATOR = new Creator<MusicLibraryTable>() {
        @Override
        public MusicLibraryTable createFromParcel(Parcel source) {
            return new MusicLibraryTable(source);
        }

        @Override
        public MusicLibraryTable[] newArray(int size) {
            return new MusicLibraryTable[size];
        }
    };

    @Override
    public String toString() {
        return "MusicLibraryTable{" +
                "id=" + id +
                ", SONG_ID='" + SONG_ID + '\'' +
                ", SONG_TITLE='" + SONG_TITLE + '\'' +
                ", SONG_ARTIST='" + SONG_ARTIST + '\'' +
                ", SONG_ALBUM='" + SONG_ALBUM + '\'' +
                ", SONG_ALBUM_ARTIST='" + SONG_ALBUM_ARTIST + '\'' +
                ", SONG_DURATION='" + SONG_DURATION + '\'' +
                ", SONG_FILE_PATH='" + SONG_FILE_PATH + '\'' +
                ", SONG_TRACK_NUMBER='" + SONG_TRACK_NUMBER + '\'' +
                ", SONG_GENRE='" + SONG_GENRE + '\'' +
                ", SONG_PLAY_COUNT='" + SONG_PLAY_COUNT + '\'' +
                ", SONG_YEAR='" + SONG_YEAR + '\'' +
                ", ALBUMS_COUNT='" + ALBUMS_COUNT + '\'' +
                ", SONGS_COUNT='" + SONGS_COUNT + '\'' +
                ", GENRES_SONG_COUNT='" + GENRES_SONG_COUNT + '\'' +
                ", SONG_LAST_MODIFIED='" + SONG_LAST_MODIFIED + '\'' +
                ", SONG_SCANNED='" + SONG_SCANNED + '\'' +
                ", BLACKLIST_STATUS='" + BLACKLIST_STATUS + '\'' +
                ", ADDED_TIMESTAMP='" + ADDED_TIMESTAMP + '\'' +
                ", RATING='" + RATING + '\'' +
                ", LAST_PLAYED_TIMESTAMP='" + LAST_PLAYED_TIMESTAMP + '\'' +
                ", SONG_SOURCE='" + SONG_SOURCE + '\'' +
                ", SONG_ALBUM_ART_PATH='" + SONG_ALBUM_ART_PATH + '\'' +
                ", SONG_DELETED='" + SONG_DELETED + '\'' +
                ", ARTIST_ART_LOCATION='" + ARTIST_ART_LOCATION + '\'' +
                ", ALBUM_ID='" + ALBUM_ID + '\'' +
                ", ARTIST_ID='" + ARTIST_ID + '\'' +
                ", GENRE_ID='" + GENRE_ID + '\'' +
                ", GENRE_SONG_COUNT='" + GENRE_SONG_COUNT + '\'' +
                ", LOCAL_COPY_PATH='" + LOCAL_COPY_PATH + '\'' +
                ", LIBRARIES='" + LIBRARIES + '\'' +
                ", SAVED_POSITION='" + SAVED_POSITION + '\'' +
                '}';
    }
    // KEEP METHODS END

}
